enableGlobalCache: true

nodeLinker: node-modules

npmScopes:
  abb:
    npmAlwaysAuth: true
    npmAuthIdent: 'ABB-BCI-PCP:qshzbvppne242gocdzfwxyppuy6xqtl7pctwiq3qbanw5iqfmrxq'
    npmRegistryServer: 'https://pkgs.dev.azure.com/ABB-BCI-PCP/PCP/_packaging/ABB-PCP-CommonHMI/npm/registry/'
  abb-hmi:
    npmAlwaysAuth: true
    npmAuthIdent: 'ABB-BCI-PCP:qshzbvppne242gocdzfwxyppuy6xqtl7pctwiq3qbanw5iqfmrxq'
    npmRegistryServer: 'https://pkgs.dev.azure.com/ABB-BCI-PCP/PCP/_packaging/ABB-PCP-CommonHMI/npm/registry/'
  abb-iom:
    npmAlwaysAuth: true
    npmAuthIdent: 'ABB-BCI-PCP:qshzbvppne242gocdzfwxyppuy6xqtl7pctwiq3qbanw5iqfmrxq'
    npmRegistryServer: 'https://pkgs.dev.azure.com/ABB-BCI-PCP/IOM/_packaging/IOM.Common/npm/registry/'

yarnPath: .yarn/releases/yarn-3.6.3.cjs
