enableGlobalCache: true

nodeLinker: node-modules

npmScopes:
  abb:
    npmAlwaysAuth: true
    npmAuthIdent: 'ABB-BCI-PCP:gavvlrvdkqdwsf3whmqcn23cz3mvmowkmwqic277bsmo55hhvzua'
    npmRegistryServer: 'https://pkgs.dev.azure.com/ABB-BCI-PCP/PCP/_packaging/ABB-PCP-CommonHMI/npm/registry/'
  abb-hmi:
    npmAlwaysAuth: true
    npmAuthIdent: 'ABB-BCI-PCP:gavvlrvdkqdwsf3whmqcn23cz3mvmowkmwqic277bsmo55hhvzua'
    npmRegistryServer: 'https://pkgs.dev.azure.com/ABB-BCI-PCP/PCP/_packaging/ABB-PCP-CommonHMI/npm/registry/'
  abb-iom:
    npmAlwaysAuth: true
    npmAuthIdent: 'ABB-BCI-PCP:gavvlrvdkqdwsf3whmqcn23cz3mvmowkmwqic277bsmo55hhvzua'
    npmRegistryServer: 'https://pkgs.dev.azure.com/ABB-BCI-PCP/IOM/_packaging/IOM.Common/npm/registry/'

yarnPath: .yarn/releases/yarn-3.6.3.cjs
